config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  namespace :admin do
    root to: "dashboard#index"
    resources :series
    resources :users
    resources :exercises
    resources :reps
    resources :next_exercises
    resources :class_sections
    resources :enrollments
  end

  namespace :student do
    root to: "dashboard#index"
    resources :exercises
    resources :reps
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_section.rb
class ClassSection
  include ApplicationNode

  property :name, required: true, unique: true

  has_many :out, :enrollments,
    type: :enrollment

  def students
    enrollments.student
  end
end

app/models/comment.rb
def get_node_by_uuid(uuid)
    Neo4j::Session.query.match('n').where('n.uuid' => uuid).return('n').first.try(:n)
end

class Comment
  include ApplicationNode

  property :text

  has_one :out, :comment_on, type: :comment, model_class: false
  has_one :out, :author, type: :author, model_class: :Student

  def comment_on_uuid=(uuid)
    self.comment_on = get_node_by_uuid(uuid)
  end
end

app/models/concerns/application_node.rb
module ApplicationNode
  extend ActiveSupport::Concern
  include Neo4j::ActiveNode
  include Neo4j::Timestamps
end

app/models/concerns/application_rel.rb
def get_node_by_uuid(uuid)
  Neo4j::Session.query.match('n').where('n.uuid' => uuid).return('n').first.try(:n)
end

module ApplicationRel
  extend ActiveSupport::Concern
  include Neo4j::ActiveRel
  include Neo4j::Timestamps

  def from_node_uuid; end
  def to_node_uuid; end

  def from_node_uuid=(uuid)
    self.from_node = get_node_by_uuid(uuid)
  end

  def to_node_uuid=(uuid)
    self.to_node = get_node_by_uuid(uuid)
  end
end

app/models/enrollment.rb
class Enrollment
  include ApplicationNode

  has_many :out, :reps, type: :rep
  has_one :in, :student, type: :enrollment
  has_one :in, :class_section, type: :enrollment
end

app/models/exercise.rb
class Exercise
  include ApplicationNode

  property :title
  property :description
  property :teachers_notes

  has_one :out, :next_exercise, rel_class: :NextExercise

  has_one :in, :previous_exercise, rel_class: :NextExercise
  has_many :in, :reps, type: :exercise

  def self.series_roots
    Neo4j::Session.query.
      match('exercise').
      match('(exercise)-[:next_exercise]->()').
      where_not(' ()-[:next_exercise]->(exercise)').
      pluck('exercise')
  end

  def next_exercise_rel
    rels(type: :next_exercise).detect do |rel|
      rel.from_node === self
    end
  end

  def previous_exercise_rel
    rels(type: :next_exercise).detect do |rel|
      rel.to_node === self
    end
  end

  def next_exercises
    query_as(:exercise).
      match('(exercise)-[:next_exercise*]->(next)').
      return('next').
      pluck('next')
  end

  def previous_exercises
    query_as(:exercise).
      match('(previous)-[:next_exercise*]->(exercise)').
      return('previous').
      pluck('previous').reverse
  end
end

app/models/exercise_participation.rb
class ExerciseParticipation
  include Neo4j::ActiveRel
  include Neo4j::Timestamps

  from_class :Person
  to_class :Exercise
  type :participated_in

  property :difficulty_rating
  property :run_rating

  validates :difficulty_rating, numericality: {
    allow_nil: true,
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than: 5,
  }

  validates :fun_rating, numericality: {
    allow_nil: true,
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than: 5,
  }
end

app/models/exercise_prerequisite.rb
class ExercisePrerequisite
  include Neo4j::ActiveRel
  include Neo4j::Timestamps

  from_class :Exercise
  to_class :Exercise

  type 'prerequisite_of'
end

app/models/next_exercise.rb
class NextExercise
  include ApplicationRel

  from_class :Exercise
  to_class :Exercise
  type :next_exercise
end

app/models/person.rb
class Person
  include Neo4j::ActiveNode
  include Neo4j::Timestamps

  property :user_id, index: :exact, unique: true

  has_many :out, :exercises_taken, rel_class: :ExerciseParticipation
end

app/models/rep.rb
class Rep
  include ApplicationNode

  has_one :in, :enrollment,
    model_class: :Enrollment,
    type: :rep

  has_one :out, :exercise,
    model_class: :Exercise,
    type: :exercise

  has_many :in, :comments, origin: :comment_on

  %w(difficulty usefulness understanding).each do |metric|
    property metric, type: Integer
    validates metric,
      numericality: {
        integer_only: true,
        allow_blank: true,
        allow_nil: true
      }

    define_method metric do
      value = super()
      if value === 0
        nil
      else
        value
      end
    end
  end
end

app/models/student.rb
class Student
  include ApplicationNode

  property :user_id
  has_many :out, :enrollments, type: :enrollment

  def exercises
    enrollments.reps.exercise
  end

  def user
    User.find(user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_ROLES = %w(admin user student)
  DEFAULT_ROLES = ['student']

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_roles

  def set_default_roles
    self.roles = DEFAULT_ROLES
  end

  def roles=(nominated_roles)
    # `&` is a set intersection in Ruby
    # Only roles that exist in `nominated_roles` and `VALID_ROLES` will be set.
    super nominated_roles & VALID_ROLES
  end

  def admin?
    roles.include?('admin')
  end

  def student?
    roles.include?('student')
  end

  def student
    @student ||= Student.find_or_create_by user_id: self.id
  end

  class NotAuthorized < Exception; end
end

app/controllers/admin/class_sections_controller.rb
class Admin::ClassSectionsController < Admin::ResourceController
  def resource_class; ClassSection end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :restrict_to_admins

  def restrict_to_admins
    unless current_user && current_user.admin?
      flash[:error] = "Not available."
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from User::NotAuthorized, with: :deny_access

  def deny_access
    flash[:error] = "You are not authorized to commit this action. Please log in."
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :restrict_to_students


  helper_method :current_student
  def current_student
    @current_student ||= current_user.student
  end

  def restrict_to_students
    unless current_user && current_user.student?
      flash[:error] = "Not available."
      redirect_to root_path
    end
  end
end

app/helpers/admin/exercises_helper.rb
module Admin::ExercisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_navigation_link(text, path)
    classname = 'admin-navigation-link'
    if respond_to?(:resources_path) && request.path.starts_with?(resources_path)
      classname << '-active'
    end

    link_to text, path, class: classname
  end

  def student_navigation_link(text, path)
    classname = 'student-navigation-link'
    if respond_to?(:resources_path) && request.path.starts_with?(resources_path)
      classname << '-active'
    end

    link_to text, path, class: classname
  end

  def partial(path, locals={})
    render partial: path, locals: locals
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/admin/class_sections/_form.html.erb
<%= f.input :name %>

app/views/admin/class_sections/edit.html.erb
<%= semantic_form_for resource, url: resource_path do |f| %>
  <%= partial 'form', f: f %>
  <%= f.submit 'Save Changes' %>
<% end %>

app/views/admin/class_sections/index.html.erb
<h1 class="admin">Admin - Class Sections</h1>
<%= link_to 'New Class', new_resource_path, class: "bttn-new" %>
<table class="admin">
  <thead>
    <th>Name</th>
    <th></th>
  </thead>

  <% resources.each do |class_section| %>
    <tr>
      <td><%= link_to resource_path(class_section) do %><%= class_section.name %><% end %></td>
      <td>
        <%= link_to "Show", resource_path(class_section), class: "bttn-show" %>
        <%= link_to "Edit", edit_resource_path(class_section), class: "bttn-edit" %>
        <%=
          link_to "Delete", resource_path(class_section),  class: "bttn-del",
            method: :delete,
            data: {
              confirm: "Are you sure?"
            }
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/class_sections/new.html.erb
<%= semantic_form_for resource, url: resources_path do |f| %>
  <%= partial 'form', f: f %>
  <%= f.submit 'Save' %>
<% end %>

app/views/admin/class_sections/show.html.erb
<p><%= link_to 'All Classes', resources_path %></p>

<h1 class="admin"><%= resource.name %></h1>
<p><%= link_to "Edit", edit_resource_path(resource), class: "bttn-edit" %></p>

<h2>Students</h2>

<%=
  semantic_form_for :enrollment,
    url: admin_enrollments_path(next_page: request.original_url) do |f|
%>
  <%= f.hidden_field :class_section, value: resource.id %>
  <%
    options = options_for_select(
      (Student.all.to_a - resource.students.to_a).collect do |student|
        [student.user.email, student.id]
      end
    )
  %>
  <%= f.select :student, options %>
  <%= f.submit 'Add Student' %>
<% end %>


<%= semantic_form_for :rep, url: admin_reps_path(next_page: request.original_url) do |f| %>
  <table class="admin">
    <thead>
      <th><input type="checkbox"></th>
      <th>Email Address</th>
      <th></th>
    </thead>

    <% resource.enrollments.each do |enrollment| %>
      <tr>
        <td>
          <%=
            f.input :enrollments,
              as: 'check_boxes',
              collection: [enrollment.id],
              label: false
          %>
        </td>
        <td><%= link_to resource_path(enrollment.student.user) do %><%= enrollment.student.user.email %><% end %></td>
        <td>
          <%= link_to "Show", resource_path(enrollment.student.user), class: "bttn-show" %>
          <%=
            link_to "Remove", resource_path(enrollment, next_page: request.original_url),  class: "bttn-del",
              method: :delete,
              data: {
                confirm: "Are you sure?"
              }
          %>
        </td>
      </tr>
    <% end %>
  </table>

  <hr />
  <h2 class="admin">Add rep (will apply to all selected students)</h2>
  <%=
    f.input :exercise,
      label: 'Pick Exercise',
      as: :select,
      include_blank: false,
      collection: Exercise.all.collect{|e| [e.title, e.id]}
  %>
  <%= f.submit 'Add Rep' %>
<% end %>