config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  namespace :admin do
    root to: "dashboard#index"
    resources :series
    resources :users
    resources :exercises
    resources :reps
    resources :next_exercises
    resources :class_sections
    resources :enrollments
  end

  namespace :student do
    root to: "dashboard#index"
    resources :exercises
    resources :reps
    resources :comments
  end

end

app/models/student.rb
class Student
  include ApplicationNode

  property :user_id
  has_many :out, :enrollments, type: :enrollment

  def exercises
    enrollments.reps.exercise
  end

  def user
    User.find(user_id)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

end

app/controllers/student/comments_controller.rb
class Student::CommentsController < Student::ResourceController
  def resource_class; Comment end

  def authorize_create!
    if @resource.comment_on.class == Rep
      @resource.comment_on.enrollment.student == current_student or raise User::NotAuthorized
      @resource.author == current_student or raise User::NotAuthorized
    else
      raise User::NotAuthorized
    end
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < StudentController
  def index
    @student = current_user.student
  end
end

app/controllers/student/exercises_controller.rb
class Student::ExercisesController < Student::ResourceController
  def resource_class; Exercise end

  def get_resources
    current_user.student.exercises
  end
end

app/controllers/student/reps_controller.rb
class Student::RepsController < Student::ResourceController
  def resource_class; Rep end

  def authorize_update!
    @resource.enrollment.student === current_student or raise User::NotAuthorized
  end
end

app/controllers/student/resource_controller.rb
class Student::ResourceController < StudentController
  include GenericResource

  def authorize_index!
    true
  end

  def route_namespace; 'student_' end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :restrict_to_students


  helper_method :current_student
  def current_student
    @current_student ||= current_user.student
  end

  def restrict_to_students
    unless current_user && current_user.student?
      flash[:error] = "Not available."
      redirect_to root_path
    end
  end
end

app/views/student/dashboard/index.html.erb
<h1> Hello Student </h1>
<p>
  <%= current_user.email %>
</p>

<h2>Your Exercises</h2>

<p>Please rate each exercise from 1-5 for diffulty and usefulness. 5 means most difficult and most useful.</p>

<p>If you have more general comments, please leave them here for individual exercises.</p>

<% counter = 1 %>

<% current_student.enrollments.each do |enrollment| %>
  <h3>Class: <%= enrollment.class_section.name %></h3>

  <% enrollment.reps.each do |rep| %>
    <% exercise = rep.exercise %>
    <div class="exercise">
      <div class="pull-right">
        <paper-button raised onclick="exercise<%= counter %>.open()">Description</paper-button>
      </div>
      <p class="exercise-title">
        <%= exercise.title %><br />
        <span class="exercise-meta">Completed <%= time_ago_in_words rep.created_at %> ago</span>
      </p>
      <p>
        <%= form_for rep, url: student_rep_path(rep, next_page: student_root_path) do |f| %>
          <%= f.select :difficulty, [['', 0]] + (1..5).map{|scale| [scale, scale] } %> Difficulty <br />
          <%= f.select :usefulness, [['', 0]] + (1..5).map{|scale| [scale, scale] } %>
          Usefulness <br />
          <%= f.submit 'Save Rating' %>
        <% end %>
      </p>
      <div>
        <% if rep.comments.any? %>
          <% rep.comments.each do |comment| %>
            <p>
              You said: <%= comment.text %>
            </p>
          <% end %>
        <% end %>
      </div>
      <p>
        <%= form_for :comment, url: student_comments_path(next_page: student_root_path) do |f| %>
          <%= f.text_area :text %>
          <%= f.hidden_field :comment_on_uuid, value: rep.id %>
          <%= f.hidden_field :author, value: current_student.id %>
          <%= f.submit "Send Comment" %>
        <% end %>
      </p>

      <paper-dialog id="exercise<%= counter %>" class="exercise-description">
        <h2><%= exercise.title %></h2>
        <paper-dialog-scrollable class="exercise-scrollable">
          <p><%= sanitize exercise.description %></p>
        </paper-dialog-scrollable>
        <div class="buttons">
          <paper-button dialog-confirm autofocus>OK</paper-button>
        </div>
      </paper-dialog>

      <% counter = counter + 1 %>
    </div>
  <% end %>
<% end %>